"""empty message

Revision ID: 2b6ffd3f4e8e
Revises: 836ced22750c
Create Date: 2019-02-01 12:21:10.644692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6ffd3f4e8e'
down_revision = '836ced22750c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
