"""empty message

Revision ID: 962f061827f3
Revises: f32d8a5560b2
Create Date: 2019-02-06 16:39:14.980943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962f061827f3'
down_revision = 'f32d8a5560b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
